version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run: |
          yarn
          yarn test
          MAPBOX_ACCESS_TOKEN=$MAPBOX_ACCESS_TOKEN yarn run build
          ssh-keyscan $LINODE_IP >> ~/.ssh/known_hosts
          ssh yes@$LINODE_IP 'mkdir -p ~/app/frontend-cookbook'
          scp -pr ./.build/* yes@$LINODE_IP:~/app/frontend-cookbook
